{% set name = "xrlint" %}
{% set version = "0.2.0" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/bcdev/xrlint/archive/v{{ version }}.tar.gz
  sha256: 73727c1ab759da7a98bd02c8cd28cc1a45d514d777f7fc25c024773e7e7d0b9a

build:
  entry_points:
    - xrlint = xrlint.cli.main:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=61.2.0
    - pip
  run:
    - python >={{ python_min }}
    - click
    - fsspec
    - pyaml
    - tabulate
    - xarray

test:
  imports:
    - xrlint
  commands:
    - pip check
    - xrlint --help
  requires:
    - python {{ python_min }}
    - pip

about:
  summary: A linter for xarray datasets.
  home: https://github.com/bcdev/xrlint
  license: MIT
  license_file: LICENSE
  description: XRLint is a linting tool and library for xarray datasets. Its design is heavily inspired by ESLint.
  dev_url: https://github.com/bcdev/xrlint

extra:
  recipe-maintainers:
    - forman
    - b-yogesh
    - TejasMorbagal
    - pont-us
    - konstntokas
